Repository DDDEastMidlandsLimited/dddem-blog, pull requests merged in 2019-10, with the labels that each got.

#22 fixed some typos and added some oxford commas
  _posts/2019-01-06-dddem-post.md
Labels: In progress, hacktober, hacktoberfest

#20 fix: spelling mistakes in 2019-03-07-building-confidence-post.md
  _posts/2019-03-07-building-confidence-post.md
Labels: hacktober, hacktoberfest

#26 Enhancement: Add a post on why we've moved from Medium
  _posts/2019-10-10-moving-from-medium.md
Labels: Blog idea, In progress

#29 Blog: Social Media Wizardry
  _posts/2019-01-08-coming-up-with-a-talk-post.md
  _posts/2019-02-08-writing-a-talk-proposal-post.md
  _posts/2019-02-23-sparkling-biographies-post.md
  _posts/2019-03-07-building-confidence-post.md
  _posts/2019-04-13-planning-structure-post.md
  _posts/2019-05-07-considering-flow-post.md
  _posts/2019-10-10-social-media-wizardry.md
  assets/img/2019-10-10/slide1.png
  assets/img/2019-10-10/tweetdeck.png
Labels: Blog idea, In progress

#32 Added blog post about how to add a blog post
  .github/contributing.md
  _posts/2019-10-10-how-to-pr-with-your-post.md
  assets/img/2019-10-10/Fork-repo.png
  assets/img/2019-10-10/Forked-repo-clone.png
  assets/img/2019-10-10/Git-clone.png
  assets/img/2019-10-10/Github-pull-request-button.png
  assets/img/2019-10-10/Posts-directory.gif
  assets/img/2019-10-10/Pull-request.png
  assets/img/2019-10-10/Push-changes.png
Labels: Blog idea, In progress

#38 Tweak colour to improve colour contrast
  _sass/base/_variables.scss
Labels: accessibility, enhancement

#42 Added PubConf Nottingham FAQ
  _posts/2019-10-15-pubconf-nottingham-faq.md
Labels: Blog idea

#41 blog post about Nottingham Tech Community
  _posts/2019-10-11-nottingham-tech-community.md
  assets/img/2019-10-11/robin-hood.jpg
Labels: Blog idea, In progress

#36 Added Google Analytics code and snippet
  _config.yml
  _includes/footer.html
  _includes/head.html
Labels: In progress, enhancement, hacktober, hacktoberfest
